In [15]:

import os
import math
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import array_to_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing import image_dataset_from_directory

from IPython.display import display

from osgeo import gdal


In [16]:
batch_size = 6 
crop_size = 512
upscale_factor = 2
input_size = crop_size // upscale_factor


In [19]:
root_dir = "/media/quothbonney/SRTM/512"

In [20]:
files = [root_dir + fname for fname in os.listdir(root_dir)]

In [14]:
# Define a Python generator function that generates random vectors
def tensor_generator(file_names):
  for i in file_names:
    yield gdal.Open(i).ReadAsArray()

# Create a TensorFlow dataset from the generator function
dataset = tf.data.Dataset.from_generator(
    lambda: tensor_generator(file_names=files),
    output_signature=tf.TensorSpec(shape=(3,), dtype=tf.float32))

# Iterate over the dataset
for vector in dataset:
    print(vector)

tf.Tensor([ 0.26591602  0.05351897 -2.4222767 ], shape=(3,), dtype=float32)
tf.Tensor([ 1.3448025  1.6343777 -0.0417584], shape=(3,), dtype=float32)
tf.Tensor([0.13694707 0.67370373 0.2637532 ], shape=(3,), dtype=float32)
tf.Tensor([ 0.1049813  -0.42401105 -0.6799734 ], shape=(3,), dtype=float32)
tf.Tensor([ 0.7612197  -0.80000794  0.89156306], shape=(3,), dtype=float32)
tf.Tensor([-0.54110926  0.23421131 -0.5313797 ], shape=(3,), dtype=float32)
tf.Tensor([ 0.3170658 -2.5229418  1.1976063], shape=(3,), dtype=float32)
tf.Tensor([1.6964629  2.423784   0.40316767], shape=(3,), dtype=float32)
tf.Tensor([ 0.813159   -1.28309    -0.77259636], shape=(3,), dtype=float32)
tf.Tensor([-1.4643902  2.258492   0.6474925], shape=(3,), dtype=float32)


2023-03-08 17:11:11.869026: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-08 17:11:11.869405: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-08 17:11:11.869508: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2023-03-08 17:11:11.869583: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2023-03-08 17:11:11.869653: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co